### ISSUE TITLE
Endpoint: POST api/messages

### ISSUE THREAD

**Issue by benna100** [HackYourFuture-CPH/chattie#16]
## User story

**Who:** **As a** developer

**What:** **I want to** be able to create a new message using a POST endpoint

**Why:** **so that we can** create a new message

## Implementation details
- Create the POST endpoint `api/messages`

These are the message details:

- channel id
- user id
- message
- created_at

**Comment by STEP0HEN** [comment]
Link to story's PR. 

https://github.com/HackYourFuture-CPH/chattie/pull/51
