### ISSUE TITLE
Backend: Get username into database and backend

### ISSUE THREAD

**Issue by benna100** [HackYourFuture-CPH/chattie#92]
## User story

**Who:** **As a** developer

**What:** **I want to** work with username in api

**Why:** **so that we can** use username

## Implementation details
- Add username into the api, database everywhere where it is used!
- There might be multiple places, fx the get, post, patch, delete and the database + seeds

**Comment by bytewiz** [comment]
@benna100 Seems like this has already been implemented will there for close the issue :v: thanks @STEP0HEN  for checking so you didn't end up doing some double work 👍
